# Generated by Django 4.2.6 on 2023-10-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название', max_length=45, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Текст заметки')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
