# Generated by Django 4.2.6 on 2023-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='Moscow', max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='date_registration',
            field=models.DateTimeField(blank=True, default='2023-01-01'),
        ),
    ]
