# Generated by Django 4.2.6 on 2023-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_address_client_date_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_registration',
            field=models.DateTimeField(blank=True, default='2023-01-01 00:00:00'),
        ),
    ]
