# Generated by Django 4.2.6 on 2023-10-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_client_date_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('date_registration', models.DateTimeField(default='2023-01-01 00:00:00')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='date_registration',
            field=models.DateTimeField(default='2023-01-01 00:00:00'),
        ),
    ]
