# Generated by Django 4.2.6 on 2023-10-22 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_alter_client_date_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
