# Generated by Django 4.2.6 on 2023-10-22 09:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_client_date_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_check', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_order', models.DateTimeField(default=datetime.datetime.now)),
                ('basket', models.ManyToManyField(to='main.product')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
