# Generated by Django 4.2.6 on 2023-10-23 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newnote',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newnote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='newnote',
            name='title',
            field=models.CharField(default='Название', max_length=45),
        ),
    ]
